//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


    public partial class Solicitantes
    {
        /// <summary>
        /// Control form1.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Control btnNuevo.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>
        /// Control gvSolicitantes.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvSolicitantes;
    }
