//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán
//     si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class WebForm1
{
    /// <summary>
    /// Control form1.
    /// </summary>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    /// <summary>
    /// Control txtRespuesta.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtRespuesta;
}
