//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio202
{
    public partial class WebForm1
    {
        /// <summary>
        /// Control form1.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Control Label1.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>
        /// Control txtN.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtN;

        /// <summary>
        /// Control btnGenerar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGenerar;

        /// <summary>
        /// Control lblError.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// Control litTabla.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTabla;
    }
}
